WebScraping/Controllers/EmploymentController.cs
using HtmlAgilityPack;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebScraping.Models.HelperModels;
using WebScraping.Models.Siniflar;

namespace WebScraping.Controllers
{
    public class EmploymentController : Controller
    {
        // GET: Employment
        WebScrapingDBEntities db = new WebScrapingDBEntities();

        public ActionResult Index(Homes model)
        {
            List<Homes> homesAllDatas = new List<Homes>();

            //Verileri okunulması istenilen web sitesinin url’ i string veri tipine dönüştürülür.
            //Url içerisindeki Xpath alanları bulunarak o alanların htmlnode olarak gelmesi sağlanır.
            //Node’ların içerisinde istenilen veriler bulunmaktadır. Bu şekilde veriler görüntülenebilir ve kaydedilebilir.

            //hepsiemlaktan çekilen veriler buradan çekiliyor.

            List<Homes> homes = new List<Homes>();
            for (int i = 3; i < 36; i++)
            {
                var web = new HtmlWeb();
                var doc = web.Load("https://www.hepsiemlak.com/kiralik?page=" + i);
                foreach (var item in doc.DocumentNode.SelectNodes("//div[@class='list-view-line']"))
                {
                    int price = 0;

                    if (item.ChildNodes[2].ChildNodes[2].ChildNodes[0].ChildNodes[0].ChildNodes[1].ChildNodes[0].InnerText == "GBP")
                    {
                        price = Convert.ToInt32(item.ChildNodes[2].ChildNodes[2].ChildNodes[0].ChildNodes[0].InnerText.Trim().Replace("GBP", "").TrimEnd().Replace(".", ""));
                    }
                    else
                    {
                        price = Convert.ToInt32(item.ChildNodes[2].ChildNodes[2].ChildNodes[0].ChildNodes[0].InnerText.Trim().Replace("TL", "").TrimEnd().Replace(".", ""));
                    }
                    string room = item.ChildNodes[2].ChildNodes[4].ChildNodes[0].ChildNodes[0].ChildNodes[0].ChildNodes[2].ChildNodes[0].InnerText.Trim();
                    int metre = Convert.ToInt32(item.ChildNodes[2].ChildNodes[4].ChildNodes[0].ChildNodes[0].ChildNodes[0].ChildNodes[2].ChildNodes[4].ChildNodes[0].InnerText.Trim().Replace("m2", "").TrimEnd().Replace(".", "").Split(' ')[0]);
                    string link = "https://www.hepsiemlak.com" + item.ChildNodes[2].ChildNodes[0].ChildNodes[0].GetAttributeValue("href", "").Trim();
                    string img = item.ChildNodes[0].ChildNodes[2].ChildNodes[2].InnerHtml.Replace("data-src=", "~").Replace("width", "~width").Replace("\"", "").Split('~')[1].Trim();

                    #region Floor


                    int floor = 0;
                    var floorDeger = item.ChildNodes[2].ChildNodes[4].ChildNodes[0].ChildNodes[0].ChildNodes[0].ChildNodes[2].ChildNodes[8].ChildNodes[0].InnerText.Trim();
                    var katDeger = floorDeger.Split('.')[0];

                    if (isInt(katDeger) == false)
                    {
                        floor = 0;
                    }
                    else if (isInt(katDeger) == true)
                    {
                        floor = Convert.ToInt32(katDeger);
                    }
                    else
                    {
                        floor = 0;
                    }


                    #endregion

                    #region Age

                    int age = 0;
                    string ageDeger = item.ChildNodes[2].ChildNodes[4].ChildNodes[0].ChildNodes[0].ChildNodes[0].ChildNodes[2].ChildNodes[6].ChildNodes[0].InnerText.Trim();

                    if (ageDeger == "Sıfır Bina")
                        age = 100;
                    else
                    {
                        age = Convert.ToInt32(ageDeger.Split(' ')[0]);
                    }

                    #endregion

                    var doc2 = web.Load(link);

                    foreach (var item2 in doc2.DocumentNode.SelectNodes("//div[@class='cont-inner']"))
                    {
                        var shortcut = item2.ChildNodes[0].ChildNodes[6].ChildNodes[2].ChildNodes[1];
                        var shortcut1 = item2.ChildNodes[0].ChildNodes[6].ChildNodes[2].ChildNodes[0];
                        string heating = "";
                        int totalFloor = 0;
                        string isFurnished = "";
                        string formHousing = "";
                        int bathroom = 0;

                        int sınır = shortcut.ChildNodes.Count;
                        int sınır1 = shortcut1.ChildNodes.Count;

                        if (sınır > sınır1)
                        {
                            sınır = sınır1;
                        }
                        for (int j = 0; j < sınır; j++)
                        {
                            var ana = shortcut.ChildNodes[j].ChildNodes[0].ChildNodes[0].InnerText.Trim();
                            var ana1 = shortcut1.ChildNodes[j].ChildNodes[0].ChildNodes[0].InnerText.Trim();

                            if (ana == "Isınma Tipi")
                            {
                                heating = shortcut.ChildNodes[j].ChildNodes[2].ChildNodes[0].InnerText.Trim();
                            }
                            else if (ana == "Kat Sayısı")
                            {
                                totalFloor = Convert.ToInt32(shortcut.ChildNodes[j].ChildNodes[2].ChildNodes[0].InnerText.Trim().Split(' ')[0]);
                            }
                            else if (ana == "Eşya Durumu")
                            {
                                isFurnished = shortcut.ChildNodes[j].ChildNodes[2].ChildNodes[0].InnerText.Trim();
                            }
                            else if (ana == "Konut Şekli")
                            {
                                formHousing = shortcut.ChildNodes[j].ChildNodes[2].ChildNodes[0].InnerText.Trim();
                            }
                            else if (ana == "Banyo Sayısı")
                            {
                                bathroom = Convert.ToInt32(shortcut.ChildNodes[j].ChildNodes[2].ChildNodes[0].InnerText.Trim().Split('+')[0]);
                            }

                            if (ana1 == "Isınma Tipi")
                            {
                                heating = shortcut1.ChildNodes[j].ChildNodes[2].ChildNodes[0].InnerText.Trim();
                            }
                            else if (ana1 == "Kat Sayısı")
                            {
                                totalFloor = Convert.ToInt32(shortcut1.ChildNodes[j].ChildNodes[2].ChildNodes[0].InnerText.Trim().Split(' ')[0]);
                            }
                            else if (ana1 == "Eşya Durumu")
                            {
                                isFurnished = shortcut1.ChildNodes[j].ChildNodes[2].ChildNodes[0].InnerText.Trim();
                            }
                            else if (ana1 == "Konut Şekli")
                            {
                                formHousing = shortcut1.ChildNodes[j].ChildNodes[2].ChildNodes[0].InnerText.Trim();
                            }

                            else if (ana1 == "Banyo Sayısı")
                            {
                                bathroom = Convert.ToInt32(shortcut1.ChildNodes[j].ChildNodes[2].ChildNodes[0].InnerText.Trim().Split('+')[0]);
                            }
                        }

                        string city = item2.ChildNodes[0].ChildNodes[4].ChildNodes[0].ChildNodes[0].ChildNodes[0].InnerText.Trim();
                        string county = item2.ChildNodes[0].ChildNodes[4].ChildNodes[0].ChildNodes[2].ChildNodes[0].InnerText.Trim();
                        string district = item2.ChildNodes[0].ChildNodes[4].ChildNodes[0].ChildNodes[4].ChildNodes[0].InnerText.Trim();

                        homes.Add(new Homes()
                        {
                            price = price,
                            city = city,
                            county = county,
                            age = age,
                            floor = floor,
                            room = room,
                            metre = metre,
                            district = district,
                            totalFloor = totalFloor,
                            heating = heating,
                            isFurnished = isFurnished,
                            formHousing = formHousing,
                            bathroom = bathroom,
                            link = link,
                            image = img
                        }); ;
                        break;
                    }
                }
            }

            //Emlakjetten çekilen veriler buradan çekiliyor.

            List<HomesSahibinden> homesEmlakJet = new List<HomesSahibinden>();
            for (int i = 1; i < 20; i++)
            {
                var web = new HtmlWeb();
                var doc = web.Load("https://www.emlakjet.com/kiralik-konut/" + i);

                foreach (var item in doc.DocumentNode.SelectNodes("//div[@class='styles_listingItem__1asTK']"))
                {
                    int price = Convert.ToInt32(item.ChildNodes[0].ChildNodes[2].ChildNodes[0].ChildNodes[2].ChildNodes[0].ChildNodes[0].ChildNodes[0].ChildNodes[0].ChildNodes[0].InnerText.Trim().Replace(".", ""));
                    string link = "https://www.emlakjet.com/" + item.ChildNodes[0].GetAttributeValue("href", "").Trim();
                    string img = item.ChildNodes[0].ChildNodes[1].ChildNodes[0].GetAttributeValue("data-src", "").Trim();
                    int metre = Convert.ToInt32(item.ChildNodes[0].ChildNodes[2].ChildNodes[0].ChildNodes[1].ChildNodes[3].ChildNodes[1].InnerText.Trim().Replace("m2", "").TrimEnd().Replace(".", "").Split(' ')[0]);

WebScraping/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <title>Konut Fiyatları ve Emlak İlanları</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Homestate &mdash; 100% Free Fully Responsive HTML5 Template by FREEHTML5.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Template by FREEHTML5.CO" />
    <meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
    <meta name="author" content="FREEHTML5.CO" />

    <meta property="og:title" content="" />
    <meta property="og:image" content="" />
    <meta property="og:url" content="" />
    <meta property="og:site_name" content="" />
    <meta property="og:description" content="" />
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="shortcut icon" href="~/Content/images/evlogo2.jpg">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,300' rel='stylesheet' type='text/css'>

    <!-- Animate.css -->
    <link rel="stylesheet" href="~/Content/css/tasarimCss/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="~/Content/css/tasarimCss/icomoon.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="~/Content/css/tasarimCss/bootstrap.css">
    <!-- Superfish -->
    <link rel="stylesheet" href="~/Content/css/tasarimCss/superfish.css">
    <!-- Flexslider  -->
    <link rel="stylesheet" href="~/Content/css/tasarimCss/flexslider.css">
    <!-- Magnific Popup -->
    <link rel="stylesheet" href="~/Content/css/tasarimCss/magnific-popup.css">
    <!-- Date Picker -->
    <link rel="stylesheet" href="~/Content/css/tasarimCss/bootstrap-datepicker.min.css">
    <!-- CS Select -->
    <link rel="stylesheet" href="~/Content/css/tasarimCss/cs-select.css">
    <link rel="stylesheet" href="~/Content/css/tasarimCss/cs-skin-border.css">

    <link rel="stylesheet" href="~/Content/css/tasarimCss/style.css">


    <!-- Modernizr JS -->
    <script src="~/Content/js/tasarimJs/modernizr-2.6.2.min.js"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="js/respond.min.js"></script>
    <![endif]-->


</head>
<body>
    <div id="fh5co-wrapper">
        <div id="fh5co-page">
            <header id="fh5co-header-section" class="sticky-banner">
                <div class="container">
                    <div class="nav-header">
                        <a href="/Home/Index" class="js-fh5co-nav-toggle fh5co-nav-toggle dark"><i></i></a>
                        <h1 id="fh5co-logo"/><a href="/Home/Index"><i class="icon-home"></i> CENG <span>Emlak</span></a></h1>
                        <!-- START #fh5co-menu-wrap -->
                        <nav id="fh5co-menu-wrap" role="navigation">
                            <ul class="sf-menu" id="fh5co-primary-menu">
                                <li>@Html.ActionLink("Ana Sayfa", "Index", "Home")</li>
                                <li>@Html.ActionLink("Veri Güncelle", "Index", "Employment")</li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </header>


            @RenderBody()


            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
            @RenderSection("scripts", required: false)

            <br />
            <br />

            <footer>
                <div id="footer" style="text-align:center">
                    <div class="container">
                        <p>&copy; @DateTime.Now.Year - Kiralık Evleri Karşılaştırma Projesi - Berna KÖSE - Edanur BATUM</p>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="~/Content/js/tasarimJs/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="~/Content/js/tasarimJs/jquery.easing.1.3.js"></script>
    <!-- Bootstrap -->
    <script src="~/Content/js/tasarimJs/bootstrap.min.js"></script>
    <!-- Waypoints -->
    <script src="~/Content/js/tasarimJs/jquery.waypoints.min.js"></script>
    <script src="~/Content/js/tasarimJs/sticky.js"></script>
    <!-- Superfish -->
    <script src="~/Content/js/tasarimJs/hoverIntent.js"></script>
    <script src="~/Content/js/tasarimJs/superfish.js"></script>
    <!-- Flexslider -->
    <script src="~/Content/js/tasarimJs/jquery.flexslider-min.js"></script>
    <!-- Date Picker -->
    <script src="~/Content/js/tasarimJs/bootstrap-datepicker.min.js"></script>
    <!-- CS Select -->
    <script src="~/Content/js/tasarimJs/classie.js"></script>
    <script src="~/Content/js/tasarimJs/selectFx.js"></script>


    <!-- Main JS -->
    <script src="~/Content/js/tasarimJs/main.js"></script>
    <script src="~/Content/js/re.js"></script>
</body>
</html>